### ISSUE TITLE
try to use hammer

### ISSUE THREAD

**Issue by aabdelsa** [ucb-bar/hammer#549]
i am trying to use hammer for my project. but i don't know how to use it. the documents are not enough. is there any example ?

**Comment by harrisonliew** [comment]
Hi, thank you so much for trying to use Hammer.

Hammer is a component of the [Chipyard](https://github.com/ucb-bar/chipyard/) framework for building chips. Chipyard's [VLSI documentation](https://chipyard.readthedocs.io/en/dev/VLSI/index.html) should give you a better idea of how Hammer is used to place and route a Sha3 accelerator.

Let us know if this is helpful or still needs improvement - we are open to constructive suggestions for how to improve Hammer's usability.

**Comment by aabdelsa** [comment]
Thanks alot for your reply.I will read tge documents and go through steps. I think you should mention that in the home page of hummer

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by edwardcwang** [comment]
You can also take a look at the documentation of Hammer itself: https://github.com/ucb-bar/hammer/tree/master/doc

**Comment by aabdelsa** [comment]
i don't understand where should i get the tool and technology plugin ? i have synopsys license and it is installed on my computer. why do i need plugin and how could i find them ?

**Comment by edwardcwang** [comment]
Hello, please send us an e-mail to discuss this further.

**Comment by harrisonliew** [comment]
#550 clarified how to request access to tool plugins. 

Please note that we only actively develop the synthesis & place-and-route flow with Cadence tools. ucb-bar/hammer-synopsys-plugin#6 is an old PR for a refactoring of the very bare plugin for Design Compiler. The plugin is also incomplete for ICC1. When you get access, we encourage you to help develop those plugins!

Lastly, we are unable to share technology plugins because we do not have 3-way NDAs with the technology vendor. You will have to set up your own plugin by referencing the included ASAP7 plugin.

**Comment by HaFred** [comment]
Hi @aabdelsa, kindly ask that did you manage to get through the Hammer flow? Will it be better than the DC? Thanks.

**Comment by edwardcwang** [comment]
Hey Frederick, I'm closing this issue for now; please feel free to reach out to us or open a new issue if you have any further questions, or encounter any further issues! Thanks again for your interest in Hammer.

**Comment by knight9898** [comment]
I have send email for plugins, but why no reply?

**Comment by edwardcwang** [comment]
Hello knight9898, thank you for your interest in Hammer! What's your name and institution? Did you include your GitHub username in your e-mail?
