### ISSUE TITLE
json schema keys inconsistently need underscores

### ISSUE THREAD

**Issue by growly** [ucb-bar/hammer#573]
Chatting to @harrisonliew, this seems to be a bug: some keys in the tech json use spaces ("gds map file") and some need underscores ("additional_drc_text")

**Comment by harrisonliew** [comment]
Furthermore, they seem to break at random times/in random situations (example above - some plugins continue to use `additional drc text` without underscores just fine). However, keys with underscores seem to always work.

**Comment by colinschmidt** [comment]
I wonder if this has to do with python versions.
It seems unlikely to be truly "random"

**Comment by colinschmidt** [comment]
Resolution: See if we can nail down the situations in which it fails and which it doesn't. Potentially writing a unit test that will test against versions of python to see if that is the issue.
Also consider making the incompatible change of requiring underscores in keys going forward.

**Comment by harrisonliew** [comment]
This is actually somewhat bypassed by this, but not a good workaround at all:
https://github.com/ucb-bar/hammer/blob/master/src/hammer-tech/library_filter.py#L14-L30

**Comment by harrisonliew** [comment]
This is due to legacy uses of spaces requiring the forked [python-jsonschema-objects](https://github.com/edwardcwang/python-jsonschema-objects/tree/f7b828956867642a3569b74fa515eb22df0ebd5e). You must not have a published version installed in your Python environment. Will investigate if there's a way to shim this to remove this dependency.

**Comment by harrisonliew** [comment]
No longer an issue in new Hammer.
