### ISSUE TITLE
Error during Synthesis using Synopsys DC

### ISSUE THREAD

**Issue by harikumar27399** [ucb-bar/hammer#595]
I'm working on setting up a Hammer flow using 180nm PDK by Tower Semiconductor Ltd. I'm using the Synopsys Tool Plugin provided by the Hammer repository. However, I'm encountering the following error message while trying to synthesize the RTL using Synopsys DC.

ValueError: Must have at least one Milkyway techfile

I have included the techfile (.tf) in the .tech.json as:
```
"lef file": "tsl_scl_180nm_dir/techfile/icc.tf",
      "provides": [{"lib_type": "technology"}]
```
@harrisonliew @colinschmidt I kindly request you to look into this and let me know whether I'm going wrong somewhere or the tool plugin is broken.

**Comment by harrisonliew** [comment]
Unfortunately, our Synopsys DC plugin has been orphaned for about 3 years now, because none of the devs actively use DC or ICC.

Anyways, to specify a Milkyway file, you need to use this in your tech JSON: https://github.com/ucb-bar/hammer/blob/12aa2d6592b3730094f4fc19dec2ffc87619afa1/src/hammer-tech/schema.json#L89, not `"lef file"`

**Comment by harikumar27399** [comment]
@harrisonliew I figured the mistake I made and rectified it. Anyways, thanks a lot for the info!!
I'll ping you in case I encounter any further intriguing errors while using Synopsys DC.

**Comment by harrisonliew** [comment]
@harikumar27399 Great, thanks. I will close this; in the future, you can submit issues to hammer-synopsys-plugins.
