### ISSUE TITLE
Cadence and synopsys plugin request and ASAP7 PDK deck. 

### ISSUE THREAD

**Issue by Waxpple** [ucb-bar/hammer#641]
Hi,

I sent the email to request the hammer cadence and Synopsys plugin. How long would it take to process?
The ASAP 7 GitHub seems not responding anymore... I sent the request for the ASAP7 calibre deck about one month ago and no response so far. Anyone knows whom to reach out to? 

Thanks!
Waxpple

**Comment by harrisonliew** [comment]
Hi Waxapple,

We have added you to the plugins repositories, and that status we see is that the invitation is awaiting your response.

I cannot provide you with the Calibre deck, unfortunately. I suspect that the request form filters out any email address that do not end in .edu. Since yours ends in .edu.tw and the other person's ends in .edu.hk, this might be why there's no response? Hopefully they will see your Github issue.

**Comment by Waxpple** [comment]
Hi,

Sorry, but I don't see any invitation. Maybe the invitation is sent to Wax**a**pple instead of Waxpple? (Without an "a"). *Maybe I should change my username to prevent this xd.
Or could you invite me via email "a0910618112@gmail.com"?

Thanks for the information on ASAP7.

Thank you!
Waxpple

**Comment by Waxpple** [comment]
> Hi Waxapple,
> 
> We have added you to the plugins repositories, and that status we see is that the invitation is awaiting your response.
> 
> I cannot provide you with the Calibre deck, unfortunately. I suspect that the request form filters out any email address that do not end in .edu. Since yours ends in .edu.tw and the other person's ends in .edu.hk, this might be why there's no response? Hopefully they will see your Github issue.


Hi,

Sorry, but I don't see any invitation. Maybe the invitation is sent to Waxapple instead of Waxpple? (Without an "a"). *Maybe I should change my username to prevent this xd.
Or could you invite me via email "[a0910618112@gmail.com](mailto:a0910618112@gmail.com)"?

Thanks for the information on ASAP7.

Thank you!
Waxpple
