### ISSUE TITLE
problems i meet in hammer set up

### ISSUE THREAD

**Issue by 1bing2** [ucb-bar/hammer#647]
when i run     git submodule update --init --recursive  this command .i got this problem.How can i solve it?

problem :   unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

**Comment by harrisonliew** [comment]
That repository is not part of Hammer. You're also not supposed to do `git submodule update --init --recursive` in Chipyard. See the [documentation for initial setup](https://chipyard.readthedocs.io/en/stable/Chipyard-Basics/Initial-Repo-Setup.html#setting-up-the-chipyard-repo). Closing this since this is a Chipyard, not Hammer issue.
